In [10]:
from data.map import map_matrix
import numpy as np
import random

goal_prime = []
son_point = set()
son = np.argwhere(map_matrix[29] == 1)
print('son:', son)
for i in son:
    son_id = i.tolist()[0]
    son_point.add(son_id)
    son_son = np.argwhere(map_matrix[son_id] == 1)
    print('son_son:', son_son)
    for j in son_son:
        son_point.add(j.tolist()[0])
print('son_point:', son_point)
goal_prime_location = random.sample(son_point, 4)

print(goal_prime_location)

son: [[24]
 [25]]
son_son: [[23]
 [25]
 [29]]
son_son: [[24]
 [29]]
son_point: {24, 25, 29, 23}
[23, 29, 25, 24]


C:\Users\12612\AppData\Local\Temp\ipykernel_34792\2998001562.py:17: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  goal_prime_location = random.sample(son_point, 4)


In [2]:
import numpy as np 
n=4
a=np.empty((n,))
b=np.empty((n,1))
print(a)
print(b)
42/5

[0. 0. 0. 0.]
[[0.]
 [0.]
 [0.]
 [0.]]


8.4

In [5]:
import torch as tr 
a = tr.randint(1, 5, (4, 1)) 
print(a.shape)
print(a)
b = a ** 2
print(b)
c = tr.randint(1, 5, (4, 1)) 
print(c)
d = tr.mul(b, c)
print(d)

torch.Size([4, 1])
tensor([[3],
        [3],
        [3],
        [2]])
tensor([[9],
        [9],
        [9],
        [4]])
tensor([[1],
        [3],
        [3],
        [1]])
tensor([[ 9],
        [27],
        [27],
        [ 4]])


In [4]:
import torch as tr 

a = tr.randint(-5, -1, (4, 1)) 
abs_a = abs(a)
print(a)
print(abs_a)

tensor([[-2],
        [-4],
        [-3],
        [-3]])
tensor([[2],
        [4],
        [3],
        [3]])
