In [1]:
import numpy as np
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
a[5] = 1
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [9]:
index = np.argwhere(a==1)
print(index.shape)
goal_location = index[0]
print(goal_location.shape)

(1, 1)
(1,)


In [21]:
from common.data.map import map_matrix
print(map_matrix[10].shape)
index = np.argwhere(map_matrix[10] == 1)
goal_location = (index[0].tolist())[0]
print(goal_location)

(34,)
9


In [27]:
init_goal = np.random.randint(0,34)
print(init_goal)

26


In [28]:
a = np.zeros((2, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
b = np.zeros((2, 4))
c = np.zeros((2, 4))
ls = [a, b, c]
print(ls)

[array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]]), array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]]), array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])]


In [32]:
import random
a = [0,1,2,3,4,5,6,7,8,9]
g_p = random.sample(a, 5)
print(g_p)

[7, 9, 5, 1, 4]


In [33]:
map_point = []
for i in range(34):
    map_point.append(i)
print(map_point)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]


In [34]:
path =[2, 3, 4]
print(list(set(map_point) - set(path)))

[0, 1, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]


In [41]:
ls = [1]
a = 1
if a not in ls:
    ls.append(a)
print(ls)

[1]


In [46]:
a = np.zeros((4, 10))
b = np.zeros((2, 10))
# a = a[np.newaxis, :]
# b = b[np.newaxis, :]
c = np.concatenate((a, b), axis=0)
print(c, c.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] (6, 10)
