In [1]:
import numpy as np
a = np.zeros((1, 10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [3]:
location_vector = np.zeros(10, dtype=int)
location_vector[1] = 1
print(location_vector)

[0 1 0 0 0 0 0 0 0 0]


In [10]:
index = np.argwhere(location_vector == 1)
print((index[0].tolist())[0])

NameError: name 'location_vector' is not defined

In [9]:
import numpy as np
a = np.zeros(10, dtype=int)
a = a[np.newaxis, :]
b = np.zeros((4, 10), dtype=int)
print(a, b)
c = np.concatenate((b, a))
print(c)

[[0 0 0 0 0 0 0 0 0 0]] [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
